# This is a basic workflow to help you get started with Actions

name: Noetic

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/README.md'
      - '**/HOWTO.md'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-18.04
    steps:
      - name: cancel running workflows
        uses: everphone-gmbh/cancel-previous-workflows@v5
        env:
          GITHUB_TOKEN: ${{ github.token }}

  # This workflow contains a single job called "build"
  install:

    name: Install uav_ros_simulation
    runs-on: ubuntu-18.04
    needs: cancel

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install
        run: ./.ci/ci_before_install.sh


  build:

    name: Build uav_ros_simulation
    runs-on: ubuntu-18.04
    needs: install

    steps:

      # Runs a set of commands using the runners shell
      - name: Build
        run: ./.ci/ci_test_build.sh

  test:

    name: Test uav_ros_simulation
    runs-on: ubuntu-18.04
    needs: build

    steps:

      # Runs a set of commands using the runners shell
      - name: Test
        run: ./.ci/ci_run_tests.sh